# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
  submodules: true

- task: Bash@3
  inputs:
    workingDirectory: external/dds/src
    displayName: 'Build DDS Library'
    failOnStderr: true
    script: |
      cp Makefiles/Makefile_linux_static Makefile
      THREADING="-DDDS_THREADS_STL" THREAD_LINK="" THREAD_COMPILE="" make -e -j
    targetType: 'inline'