# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
  submodules: true

- bash:
  workingDirectory: external/dds/src
  displayName: 'Build DDS Library'
  failOnStderr: true
  script: |
    cp Makefiles/Makefile_linux_static Makefile
    make
  targetType: 'inline'